// Arama sayfası için sektör, ülke ve şehir verileri

export const sectors = [
  { value: "restaurant", label: "Restoran" },
  { value: "cafe", label: "Kafe" },
  { value: "hotel", label: "Otel" },
  { value: "market", label: "Market" },
  { value: "pharmacy", label: "Eczane" },
  { value: "florist", label: "Çiçekçi" },
  { value: "bakery", label: "Fırın" },
  { value: "butcher", label: "Kasap" },
  { value: "barber", label: "Berber" },
  { value: "beauty_salon", label: "Güzellik Salonu" },
  { value: "gym", label: "Spor Salonu" },
  { value: "clinic", label: "Klinik" },
  { value: "dentist", label: "Diş Kliniği" },
  { value: "veterinary", label: "Veteriner" },
  { value: "pet_shop", label: "Pet Shop" },
  { value: "bookstore", label: "Kitapçı" },
  { value: "stationery", label: "Kırtasiye" },
  { value: "electronics", label: "Elektronik" },
  { value: "clothing", label: "Giyim" },
  { value: "shoe_store", label: "Ayakkabı" },
  { value: "jewelry", label: "Kuyumcu" },
  { value: "furniture", label: "Mobilya" },
  { value: "hardware", label: "Hırdavat" },
  { value: "car_repair", label: "Oto Tamir" },
  { value: "car_wash", label: "Oto Yıkama" },
  { value: "real_estate", label: "Emlak" },
  { value: "insurance", label: "Sigorta" },
  { value: "bank", label: "Banka" },
  { value: "lawyer", label: "Avukat" },
  { value: "accountant", label: "Muhasebe" },
]

export const countries = [
  { value: "turkey", label: "Türkiye" },
  { value: "usa", label: "Amerika Birleşik Devletleri" },
  { value: "germany", label: "Almanya" },
  { value: "uk", label: "İngiltere" },
  { value: "france", label: "Fransa" },
  { value: "italy", label: "İtalya" },
  { value: "spain", label: "İspanya" },
  { value: "netherlands", label: "Hollanda" },
  { value: "belgium", label: "Belçika" },
  { value: "austria", label: "Avusturya" },
  { value: "switzerland", label: "İsviçre" },
  { value: "poland", label: "Polonya" },
  { value: "czech", label: "Çek Cumhuriyeti" },
  { value: "greece", label: "Yunanistan" },
  { value: "portugal", label: "Portekiz" },
  { value: "sweden", label: "İsveç" },
  { value: "norway", label: "Norveç" },
  { value: "denmark", label: "Danimarka" },
  { value: "finland", label: "Finlandiya" },
  { value: "ireland", label: "İrlanda" },
]

// Ülkelere göre şehirler
export const citiesByCountry: Record<string, { value: string; label: string }[]> = {
  turkey: [
    { value: "adana", label: "Adana" },
    { value: "adiyaman", label: "Adıyaman" },
    { value: "afyonkarahisar", label: "Afyonkarahisar" },
    { value: "agri", label: "Ağrı" },
    { value: "aksaray", label: "Aksaray" },
    { value: "amasya", label: "Amasya" },
    { value: "ankara", label: "Ankara" },
    { value: "antalya", label: "Antalya" },
    { value: "ardahan", label: "Ardahan" },
    { value: "artvin", label: "Artvin" },
    { value: "aydin", label: "Aydın" },
    { value: "balikesir", label: "Balıkesir" },
    { value: "bartin", label: "Bartın" },
    { value: "batman", label: "Batman" },
    { value: "bayburt", label: "Bayburt" },
    { value: "bilecik", label: "Bilecik" },
    { value: "bingol", label: "Bingöl" },
    { value: "bitlis", label: "Bitlis" },
    { value: "bolu", label: "Bolu" },
    { value: "burdur", label: "Burdur" },
    { value: "bursa", label: "Bursa" },
    { value: "canakkale", label: "Çanakkale" },
    { value: "cankiri", label: "Çankırı" },
    { value: "corum", label: "Çorum" },
    { value: "denizli", label: "Denizli" },
    { value: "diyarbakir", label: "Diyarbakır" },
    { value: "duzce", label: "Düzce" },
    { value: "edirne", label: "Edirne" },
    { value: "elazig", label: "Elazığ" },
    { value: "erzincan", label: "Erzincan" },
    { value: "erzurum", label: "Erzurum" },
    { value: "eskisehir", label: "Eskişehir" },
    { value: "gaziantep", label: "Gaziantep" },
    { value: "giresun", label: "Giresun" },
    { value: "gumushane", label: "Gümüşhane" },
    { value: "hakkari", label: "Hakkari" },
    { value: "hatay", label: "Hatay" },
    { value: "igdir", label: "Iğdır" },
    { value: "isparta", label: "Isparta" },
    { value: "istanbul", label: "İstanbul" },
    { value: "izmir", label: "İzmir" },
    { value: "kahramanmaras", label: "Kahramanmaraş" },
    { value: "karabuk", label: "Karabük" },
    { value: "karaman", label: "Karaman" },
    { value: "kars", label: "Kars" },
    { value: "kastamonu", label: "Kastamonu" },
    { value: "kayseri", label: "Kayseri" },
    { value: "kilis", label: "Kilis" },
    { value: "kirikkale", label: "Kırıkkale" },
    { value: "kirklareli", label: "Kırklareli" },
    { value: "kirsehir", label: "Kırşehir" },
    { value: "kocaeli", label: "Kocaeli" },
    { value: "konya", label: "Konya" },
    { value: "kutahya", label: "Kütahya" },
    { value: "malatya", label: "Malatya" },
    { value: "manisa", label: "Manisa" },
    { value: "mardin", label: "Mardin" },
    { value: "mersin", label: "Mersin" },
    { value: "mugla", label: "Muğla" },
    { value: "mus", label: "Muş" },
    { value: "nevsehir", label: "Nevşehir" },
    { value: "nigde", label: "Niğde" },
    { value: "ordu", label: "Ordu" },
    { value: "osmaniye", label: "Osmaniye" },
    { value: "rize", label: "Rize" },
    { value: "sakarya", label: "Sakarya" },
    { value: "samsun", label: "Samsun" },
    { value: "sanliurfa", label: "Şanlıurfa" },
    { value: "siirt", label: "Siirt" },
    { value: "sinop", label: "Sinop" },
    { value: "sirnak", label: "Şırnak" },
    { value: "sivas", label: "Sivas" },
    { value: "tekirdag", label: "Tekirdağ" },
    { value: "tokat", label: "Tokat" },
    { value: "trabzon", label: "Trabzon" },
    { value: "tunceli", label: "Tunceli" },
    { value: "usak", label: "Uşak" },
    { value: "van", label: "Van" },
    { value: "yalova", label: "Yalova" },
    { value: "yozgat", label: "Yozgat" },
    { value: "zonguldak", label: "Zonguldak" },
  ],
  usa: [
    { value: "new-york", label: "New York" },
    { value: "los-angeles", label: "Los Angeles" },
    { value: "chicago", label: "Chicago" },
    { value: "houston", label: "Houston" },
    { value: "phoenix", label: "Phoenix" },
    { value: "philadelphia", label: "Philadelphia" },
    { value: "san-antonio", label: "San Antonio" },
    { value: "san-diego", label: "San Diego" },
    { value: "dallas", label: "Dallas" },
    { value: "san-jose", label: "San Jose" },
    { value: "austin", label: "Austin" },
    { value: "jacksonville", label: "Jacksonville" },
    { value: "san-francisco", label: "San Francisco" },
    { value: "columbus", label: "Columbus" },
    { value: "indianapolis", label: "Indianapolis" },
    { value: "seattle", label: "Seattle" },
    { value: "denver", label: "Denver" },
    { value: "washington", label: "Washington D.C." },
    { value: "boston", label: "Boston" },
    { value: "nashville", label: "Nashville" },
  ],
  germany: [
    { value: "berlin", label: "Berlin" },
    { value: "hamburg", label: "Hamburg" },
    { value: "munich", label: "Münih" },
    { value: "cologne", label: "Köln" },
    { value: "frankfurt", label: "Frankfurt" },
    { value: "stuttgart", label: "Stuttgart" },
    { value: "dusseldorf", label: "Düsseldorf" },
    { value: "dortmund", label: "Dortmund" },
    { value: "essen", label: "Essen" },
    { value: "leipzig", label: "Leipzig" },
    { value: "bremen", label: "Bremen" },
    { value: "dresden", label: "Dresden" },
    { value: "hannover", label: "Hannover" },
    { value: "nuremberg", label: "Nürnberg" },
  ],
  uk: [
    { value: "london", label: "Londra" },
    { value: "birmingham", label: "Birmingham" },
    { value: "manchester", label: "Manchester" },
    { value: "glasgow", label: "Glasgow" },
    { value: "liverpool", label: "Liverpool" },
    { value: "edinburgh", label: "Edinburgh" },
    { value: "leeds", label: "Leeds" },
    { value: "bristol", label: "Bristol" },
    { value: "sheffield", label: "Sheffield" },
    { value: "cardiff", label: "Cardiff" },
    { value: "belfast", label: "Belfast" },
    { value: "newcastle", label: "Newcastle" },
  ],
  france: [
    { value: "paris", label: "Paris" },
    { value: "marseille", label: "Marsilya" },
    { value: "lyon", label: "Lyon" },
    { value: "toulouse", label: "Toulouse" },
    { value: "nice", label: "Nice" },
    { value: "nantes", label: "Nantes" },
    { value: "strasbourg", label: "Strasbourg" },
    { value: "montpellier", label: "Montpellier" },
    { value: "bordeaux", label: "Bordeaux" },
    { value: "lille", label: "Lille" },
  ],
  italy: [
    { value: "rome", label: "Roma" },
    { value: "milan", label: "Milano" },
    { value: "naples", label: "Napoli" },
    { value: "turin", label: "Torino" },
    { value: "palermo", label: "Palermo" },
    { value: "genoa", label: "Cenova" },
    { value: "bologna", label: "Bologna" },
    { value: "florence", label: "Floransa" },
    { value: "venice", label: "Venedik" },
    { value: "verona", label: "Verona" },
  ],
  spain: [
    { value: "madrid", label: "Madrid" },
    { value: "barcelona", label: "Barselona" },
    { value: "valencia", label: "Valencia" },
    { value: "seville", label: "Sevilla" },
    { value: "zaragoza", label: "Zaragoza" },
    { value: "malaga", label: "Malaga" },
    { value: "murcia", label: "Murcia" },
    { value: "palma", label: "Palma" },
    { value: "bilbao", label: "Bilbao" },
    { value: "alicante", label: "Alicante" },
  ],
  netherlands: [
    { value: "amsterdam", label: "Amsterdam" },
    { value: "rotterdam", label: "Rotterdam" },
    { value: "the-hague", label: "Den Haag" },
    { value: "utrecht", label: "Utrecht" },
    { value: "eindhoven", label: "Eindhoven" },
    { value: "groningen", label: "Groningen" },
    { value: "tilburg", label: "Tilburg" },
  ],
  belgium: [
    { value: "brussels", label: "Brüksel" },
    { value: "antwerp", label: "Antwerp" },
    { value: "ghent", label: "Ghent" },
    { value: "bruges", label: "Bruges" },
    { value: "liege", label: "Liège" },
  ],
  austria: [
    { value: "vienna", label: "Viyana" },
    { value: "graz", label: "Graz" },
    { value: "linz", label: "Linz" },
    { value: "salzburg", label: "Salzburg" },
    { value: "innsbruck", label: "Innsbruck" },
  ],
  switzerland: [
    { value: "zurich", label: "Zürih" },
    { value: "geneva", label: "Cenevre" },
    { value: "basel", label: "Basel" },
    { value: "bern", label: "Bern" },
    { value: "lausanne", label: "Lozan" },
  ],
  poland: [
    { value: "warsaw", label: "Varşova" },
    { value: "krakow", label: "Krakow" },
    { value: "wroclaw", label: "Wrocław" },
    { value: "poznan", label: "Poznań" },
    { value: "gdansk", label: "Gdańsk" },
  ],
  czech: [
    { value: "prague", label: "Prag" },
    { value: "brno", label: "Brno" },
    { value: "ostrava", label: "Ostrava" },
    { value: "plzen", label: "Plzeň" },
  ],
  greece: [
    { value: "athens", label: "Atina" },
    { value: "thessaloniki", label: "Selanik" },
    { value: "patras", label: "Patras" },
    { value: "heraklion", label: "Heraklion" },
  ],
  portugal: [
    { value: "lisbon", label: "Lizbon" },
    { value: "porto", label: "Porto" },
    { value: "braga", label: "Braga" },
    { value: "coimbra", label: "Coimbra" },
  ],
  sweden: [
    { value: "stockholm", label: "Stockholm" },
    { value: "gothenburg", label: "Göteborg" },
    { value: "malmo", label: "Malmö" },
    { value: "uppsala", label: "Uppsala" },
  ],
  norway: [
    { value: "oslo", label: "Oslo" },
    { value: "bergen", label: "Bergen" },
    { value: "trondheim", label: "Trondheim" },
    { value: "stavanger", label: "Stavanger" },
  ],
  denmark: [
    { value: "copenhagen", label: "Kopenhag" },
    { value: "aarhus", label: "Aarhus" },
    { value: "odense", label: "Odense" },
    { value: "aalborg", label: "Aalborg" },
  ],
  finland: [
    { value: "helsinki", label: "Helsinki" },
    { value: "espoo", label: "Espoo" },
    { value: "tampere", label: "Tampere" },
    { value: "vantaa", label: "Vantaa" },
  ],
  ireland: [
    { value: "dublin", label: "Dublin" },
    { value: "cork", label: "Cork" },
    { value: "limerick", label: "Limerick" },
    { value: "galway", label: "Galway" },
  ],
}

// Geriye dönük uyumluluk için (eski cities export'u)
export const cities = citiesByCountry.turkey

// İlçeler kaldırıldı - artık kullanılmıyor
export const districts: Record<string, { value: string; label: string }[]> = {}
